// Request get data Login
export const REQUEST_GET_DATA_LOGIN = 'REQUEST_GET_DATA_LOGIN';
export const REQUEST_GET_DATA_LOGIN_SUCCESS = 'REQUEST_GET_DATA_LOGIN_SUCCESS';
export const REQUEST_GET_DATA_LOGIN_FAILED = 'REQUEST_GET_DATA_LOGIN_FAILED';
