// Request get data Login
export const REQUEST_LIST_PRODUCTS = 'REQUEST_LIST_PRODUCTS';
export const REQUEST_LIST_PRODUCTS_SUCCESS = 'REQUEST_LIST_PRODUCTS_SUCCESS';
export const REQUEST_LIST_PRODUCTS_FAILED = 'REQUEST_LIST_PRODUCTS_FAILED';
